@DisplayConfigurator.Api_HostAddress = http://localhost:5007

GET {{DisplayConfigurator.Api_HostAddress}}/api/cabinets
Accept: application/json

###

GET {{DisplayConfigurator.Api_HostAddress}}/api/cabinets/series
Accept: application/json

###
